apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: nprbeyzf1-dotnet-basic
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.cluster-rnhxb.rnhxb.sandbox1734.opentlc.com/rhtap/rhtap-qe:44de4659f1578bc099058c33f2cf3746d44f22ec@sha256:aefcdc6c7487173ad6bc8e25111e9e621ba0a951f1787909b70f11558eb28663
          name: container-image
